# SonarQube Configuration for GadgetStock
sonar.projectKey=SukmadiArdi_GadgetStock-Teori
sonar.projectName=GadgetStock POS & Inventory
sonar.projectVersion=1.0.0
sonar.sources=public/js,api,server.js
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.mjs
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,docs/**,stitch_screens/**
sonar.javascript.environments=browser,node
